// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldProfileURL holds the string denoting the profileurl field in the database.
	FieldProfileURL = "profile_url"
	// FieldPlan holds the string denoting the plan field in the database.
	FieldPlan = "plan"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProcessingData holds the string denoting the processingdata field in the database.
	FieldProcessingData = "processing_data"
	// EdgePlanners holds the string denoting the planners edge name in mutations.
	EdgePlanners = "planners"
	// EdgeOwnedChatrooms holds the string denoting the owned_chatrooms edge name in mutations.
	EdgeOwnedChatrooms = "owned_chatrooms"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PlannersTable is the table that holds the planners relation/edge.
	PlannersTable = "planners"
	// PlannersInverseTable is the table name for the Planner entity.
	// It exists in this package in order to avoid circular dependency with the "planner" package.
	PlannersInverseTable = "planners"
	// PlannersColumn is the table column denoting the planners relation/edge.
	PlannersColumn = "user_planners"
	// OwnedChatroomsTable is the table that holds the owned_chatrooms relation/edge.
	OwnedChatroomsTable = "chatrooms"
	// OwnedChatroomsInverseTable is the table name for the Chatroom entity.
	// It exists in this package in order to avoid circular dependency with the "chatroom" package.
	OwnedChatroomsInverseTable = "chatrooms"
	// OwnedChatroomsColumn is the table column denoting the owned_chatrooms relation/edge.
	OwnedChatroomsColumn = "user_owned_chatrooms"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldProfileURL,
	FieldPlan,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProcessingData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// ProfileURLValidator is a validator for the "profileURL" field. It is called by the builders before save.
	ProfileURLValidator func(string) error
	// DefaultPlan holds the default value on creation for the "plan" field.
	DefaultPlan string
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByProfileURL orders the results by the profileURL field.
func ByProfileURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileURL, opts...).ToFunc()
}

// ByPlan orders the results by the plan field.
func ByPlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlan, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProcessingData orders the results by the processingData field.
func ByProcessingData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessingData, opts...).ToFunc()
}

// ByPlannersCount orders the results by planners count.
func ByPlannersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlannersStep(), opts...)
	}
}

// ByPlanners orders the results by planners terms.
func ByPlanners(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlannersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOwnedChatroomsCount orders the results by owned_chatrooms count.
func ByOwnedChatroomsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOwnedChatroomsStep(), opts...)
	}
}

// ByOwnedChatrooms orders the results by owned_chatrooms terms.
func ByOwnedChatrooms(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnedChatroomsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlannersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlannersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlannersTable, PlannersColumn),
	)
}
func newOwnedChatroomsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnedChatroomsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OwnedChatroomsTable, OwnedChatroomsColumn),
	)
}
