// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dimiplan-backend/ent/chatroom"
	"dimiplan-backend/ent/message"
	"dimiplan-backend/ent/planner"
	"dimiplan-backend/ent/schema"
	"dimiplan-backend/ent/task"
	"dimiplan-backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatroomFields := schema.Chatroom{}.Fields()
	_ = chatroomFields
	// chatroomDescName is the schema descriptor for name field.
	chatroomDescName := chatroomFields[0].Descriptor()
	// chatroom.NameValidator is a validator for the "name" field. It is called by the builders before save.
	chatroom.NameValidator = chatroomDescName.Validators[0].(func(string) error)
	// chatroomDescCreatedAt is the schema descriptor for createdAt field.
	chatroomDescCreatedAt := chatroomFields[1].Descriptor()
	// chatroom.DefaultCreatedAt holds the default value on creation for the createdAt field.
	chatroom.DefaultCreatedAt = chatroomDescCreatedAt.Default.(func() time.Time)
	// chatroomDescUpdatedAt is the schema descriptor for updatedAt field.
	chatroomDescUpdatedAt := chatroomFields[2].Descriptor()
	// chatroom.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	chatroom.DefaultUpdatedAt = chatroomDescUpdatedAt.Default.(func() time.Time)
	// chatroom.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	chatroom.UpdateDefaultUpdatedAt = chatroomDescUpdatedAt.UpdateDefault.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescSender is the schema descriptor for sender field.
	messageDescSender := messageFields[0].Descriptor()
	// message.SenderValidator is a validator for the "sender" field. It is called by the builders before save.
	message.SenderValidator = messageDescSender.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for createdAt field.
	messageDescCreatedAt := messageFields[2].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the createdAt field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updatedAt field.
	messageDescUpdatedAt := messageFields[3].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	plannerFields := schema.Planner{}.Fields()
	_ = plannerFields
	// plannerDescName is the schema descriptor for name field.
	plannerDescName := plannerFields[1].Descriptor()
	// planner.NameValidator is a validator for the "name" field. It is called by the builders before save.
	planner.NameValidator = plannerDescName.Validators[0].(func(string) error)
	// plannerDescCreatedAt is the schema descriptor for createdAt field.
	plannerDescCreatedAt := plannerFields[2].Descriptor()
	// planner.DefaultCreatedAt holds the default value on creation for the createdAt field.
	planner.DefaultCreatedAt = plannerDescCreatedAt.Default.(func() time.Time)
	// plannerDescUpdatedAt is the schema descriptor for updatedAt field.
	plannerDescUpdatedAt := plannerFields[3].Descriptor()
	// planner.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	planner.DefaultUpdatedAt = plannerDescUpdatedAt.Default.(func() time.Time)
	// planner.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	planner.UpdateDefaultUpdatedAt = plannerDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[1].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[2].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(int)
	// taskDescCreatedAt is the schema descriptor for createdAt field.
	taskDescCreatedAt := taskFields[3].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the createdAt field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updatedAt field.
	taskDescUpdatedAt := taskFields[4].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescProfileURL is the schema descriptor for profileURL field.
	userDescProfileURL := userFields[3].Descriptor()
	// user.ProfileURLValidator is a validator for the "profileURL" field. It is called by the builders before save.
	user.ProfileURLValidator = userDescProfileURL.Validators[0].(func(string) error)
	// userDescPlan is the schema descriptor for plan field.
	userDescPlan := userFields[4].Descriptor()
	// user.DefaultPlan holds the default value on creation for the plan field.
	user.DefaultPlan = userDescPlan.Default.(string)
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updatedAt field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
