// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dimiplan-backend/ent/chat"
	"dimiplan-backend/ent/chatroom"
	"dimiplan-backend/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRoomCreate is the builder for creating a ChatRoom entity.
type ChatRoomCreate struct {
	config
	mutation *ChatRoomMutation
	hooks    []Hook
}

// SetOwner sets the "owner" field.
func (_c *ChatRoomCreate) SetOwner(v string) *ChatRoomCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ChatRoomCreate) SetType(v string) *ChatRoomCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ChatRoomCreate) SetName(v string) *ChatRoomCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsProcessing sets the "isProcessing" field.
func (_c *ChatRoomCreate) SetIsProcessing(v bool) *ChatRoomCreate {
	_c.mutation.SetIsProcessing(v)
	return _c
}

// SetNillableIsProcessing sets the "isProcessing" field if the given value is not nil.
func (_c *ChatRoomCreate) SetNillableIsProcessing(v *bool) *ChatRoomCreate {
	if v != nil {
		_c.SetIsProcessing(*v)
	}
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *ChatRoomCreate) SetCreatedAt(v time.Time) *ChatRoomCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *ChatRoomCreate) SetNillableCreatedAt(v *time.Time) *ChatRoomCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *ChatRoomCreate) SetUpdatedAt(v time.Time) *ChatRoomCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *ChatRoomCreate) SetNillableUpdatedAt(v *time.Time) *ChatRoomCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ChatRoomCreate) SetUserID(id string) *ChatRoomCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatRoomCreate) SetUser(v *User) *ChatRoomCreate {
	return _c.SetUserID(v.ID)
}

// AddChatIDs adds the "chats" edge to the Chat entity by IDs.
func (_c *ChatRoomCreate) AddChatIDs(ids ...int) *ChatRoomCreate {
	_c.mutation.AddChatIDs(ids...)
	return _c
}

// AddChats adds the "chats" edges to the Chat entity.
func (_c *ChatRoomCreate) AddChats(v ...*Chat) *ChatRoomCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatIDs(ids...)
}

// Mutation returns the ChatRoomMutation object of the builder.
func (_c *ChatRoomCreate) Mutation() *ChatRoomMutation {
	return _c.mutation
}

// Save creates the ChatRoom in the database.
func (_c *ChatRoomCreate) Save(ctx context.Context) (*ChatRoom, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatRoomCreate) SaveX(ctx context.Context) *ChatRoom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatRoomCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatRoomCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatRoomCreate) defaults() {
	if _, ok := _c.mutation.IsProcessing(); !ok {
		v := chatroom.DefaultIsProcessing
		_c.mutation.SetIsProcessing(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatroom.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatroom.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatRoomCreate) check() error {
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "ChatRoom.owner"`)}
	}
	if v, ok := _c.mutation.Owner(); ok {
		if err := chatroom.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ChatRoom.type"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChatRoom.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := chatroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsProcessing(); !ok {
		return &ValidationError{Name: "isProcessing", err: errors.New(`ent: missing required field "ChatRoom.isProcessing"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "ChatRoom.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "ChatRoom.updatedAt"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatRoom.user"`)}
	}
	return nil
}

func (_c *ChatRoomCreate) sqlSave(ctx context.Context) (*ChatRoom, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatRoomCreate) createSpec() (*ChatRoom, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatRoom{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatroom.Table, sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(chatroom.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(chatroom.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chatroom.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsProcessing(); ok {
		_spec.SetField(chatroom.FieldIsProcessing, field.TypeBool, value)
		_node.IsProcessing = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatroom.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatroom.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroom.UserTable,
			Columns: []string{chatroom.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_chatrooms = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.ChatsTable,
			Columns: []string{chatroom.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatRoomCreateBulk is the builder for creating many ChatRoom entities in bulk.
type ChatRoomCreateBulk struct {
	config
	err      error
	builders []*ChatRoomCreate
}

// Save creates the ChatRoom entities in the database.
func (_c *ChatRoomCreateBulk) Save(ctx context.Context) ([]*ChatRoom, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatRoom, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatRoomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatRoomCreateBulk) SaveX(ctx context.Context) []*ChatRoom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatRoomCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatRoomCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
