// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dimiplan-backend/ent/chatroom"
	"dimiplan-backend/ent/user"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Chatroom is the model entity for the Chatroom schema.
type Chatroom struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"-"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatroomQuery when eager-loading is set.
	Edges          ChatroomEdges `json:"-"`
	user_chatrooms *string
	selectValues   sql.SelectValues
}

// ChatroomEdges holds the relations/edges for other nodes in the graph.
type ChatroomEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatroomEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e ChatroomEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[1] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Chatroom) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatroom.FieldID:
			values[i] = new(sql.NullInt64)
		case chatroom.FieldName:
			values[i] = new(sql.NullString)
		case chatroom.FieldCreatedAt, chatroom.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case chatroom.ForeignKeys[0]: // user_chatrooms
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Chatroom fields.
func (_m *Chatroom) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatroom.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chatroom.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case chatroom.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chatroom.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case chatroom.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_chatrooms", values[i])
			} else if value.Valid {
				_m.user_chatrooms = new(string)
				*_m.user_chatrooms = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Chatroom.
// This includes values selected through modifiers, order, etc.
func (_m *Chatroom) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Chatroom entity.
func (_m *Chatroom) QueryUser() *UserQuery {
	return NewChatroomClient(_m.config).QueryUser(_m)
}

// QueryMessages queries the "messages" edge of the Chatroom entity.
func (_m *Chatroom) QueryMessages() *MessageQuery {
	return NewChatroomClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this Chatroom.
// Note that you need to call Chatroom.Unwrap() before calling this method if this Chatroom
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Chatroom) Update() *ChatroomUpdateOne {
	return NewChatroomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Chatroom entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Chatroom) Unwrap() *Chatroom {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Chatroom is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Chatroom) String() string {
	var builder strings.Builder
	builder.WriteString("Chatroom(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MarshalJSON implements the json.Marshaler interface.
func (_m *Chatroom) MarshalJSON() ([]byte, error) {
	type Alias Chatroom
	return json.Marshal(&struct {
		*Alias
		ChatroomEdges
	}{
		Alias:         (*Alias)(_m),
		ChatroomEdges: _m.Edges,
	})
}

// Chatrooms is a parsable slice of Chatroom.
type Chatrooms []*Chatroom
