// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dimiplan-backend/ent/chat"
	"dimiplan-backend/ent/chatroom"
	"dimiplan-backend/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatUpdate is the builder for updating Chat entities.
type ChatUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (_u *ChatUpdate) Where(ps ...predicate.Chat) *ChatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSender sets the "sender" field.
func (_u *ChatUpdate) SetSender(v string) *ChatUpdate {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *ChatUpdate) SetNillableSender(v *string) *ChatUpdate {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ChatUpdate) SetMessage(v string) *ChatUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ChatUpdate) SetNillableMessage(v *string) *ChatUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *ChatUpdate) SetUpdatedAt(v time.Time) *ChatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChatroomID sets the "chatroom" edge to the ChatRoom entity by ID.
func (_u *ChatUpdate) SetChatroomID(id int) *ChatUpdate {
	_u.mutation.SetChatroomID(id)
	return _u
}

// SetChatroom sets the "chatroom" edge to the ChatRoom entity.
func (_u *ChatUpdate) SetChatroom(v *ChatRoom) *ChatUpdate {
	return _u.SetChatroomID(v.ID)
}

// Mutation returns the ChatMutation object of the builder.
func (_u *ChatUpdate) Mutation() *ChatMutation {
	return _u.mutation
}

// ClearChatroom clears the "chatroom" edge to the ChatRoom entity.
func (_u *ChatUpdate) ClearChatroom() *ChatUpdate {
	_u.mutation.ClearChatroom()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatUpdate) check() error {
	if v, ok := _u.mutation.Sender(); ok {
		if err := chat.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "Chat.sender": %w`, err)}
		}
	}
	if _u.mutation.ChatroomCleared() && len(_u.mutation.ChatroomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chat.chatroom"`)
	}
	return nil
}

func (_u *ChatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(chat.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(chat.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChatroomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.ChatroomTable,
			Columns: []string{chat.ChatroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.ChatroomTable,
			Columns: []string{chat.ChatroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatUpdateOne is the builder for updating a single Chat entity.
type ChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMutation
}

// SetSender sets the "sender" field.
func (_u *ChatUpdateOne) SetSender(v string) *ChatUpdateOne {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *ChatUpdateOne) SetNillableSender(v *string) *ChatUpdateOne {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ChatUpdateOne) SetMessage(v string) *ChatUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ChatUpdateOne) SetNillableMessage(v *string) *ChatUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *ChatUpdateOne) SetUpdatedAt(v time.Time) *ChatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChatroomID sets the "chatroom" edge to the ChatRoom entity by ID.
func (_u *ChatUpdateOne) SetChatroomID(id int) *ChatUpdateOne {
	_u.mutation.SetChatroomID(id)
	return _u
}

// SetChatroom sets the "chatroom" edge to the ChatRoom entity.
func (_u *ChatUpdateOne) SetChatroom(v *ChatRoom) *ChatUpdateOne {
	return _u.SetChatroomID(v.ID)
}

// Mutation returns the ChatMutation object of the builder.
func (_u *ChatUpdateOne) Mutation() *ChatMutation {
	return _u.mutation
}

// ClearChatroom clears the "chatroom" edge to the ChatRoom entity.
func (_u *ChatUpdateOne) ClearChatroom() *ChatUpdateOne {
	_u.mutation.ClearChatroom()
	return _u
}

// Where appends a list predicates to the ChatUpdate builder.
func (_u *ChatUpdateOne) Where(ps ...predicate.Chat) *ChatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatUpdateOne) Select(field string, fields ...string) *ChatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Chat entity.
func (_u *ChatUpdateOne) Save(ctx context.Context) (*Chat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatUpdateOne) SaveX(ctx context.Context) *Chat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatUpdateOne) check() error {
	if v, ok := _u.mutation.Sender(); ok {
		if err := chat.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "Chat.sender": %w`, err)}
		}
	}
	if _u.mutation.ChatroomCleared() && len(_u.mutation.ChatroomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chat.chatroom"`)
	}
	return nil
}

func (_u *ChatUpdateOne) sqlSave(ctx context.Context) (_node *Chat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chat.FieldID)
		for _, f := range fields {
			if !chat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(chat.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(chat.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChatroomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.ChatroomTable,
			Columns: []string{chat.ChatroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatroomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.ChatroomTable,
			Columns: []string{chat.ChatroomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
